server:
  port: 8082
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:  zipkin:    base-url: http://192.168.99.100:9411/
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true